export const mappingContinent: Record<string, string> = {
  아프리카: "AFRICA",
  아시아: "ASIA",
  유럽: "EUROPE",
  오세아니아: "AUSTRALIA",
  북미: "NORTH_AMERICA",
  남미: "SOUTH_AMERICA",
  남극: "ANTARCTIC",
  AFRICA: "아프리카",
  ASIA: "아시아",
  EUROPE: "유럽",
  AUSTRALIA: "오세아니아",
  NORTH_AMERICA: "북미",
  SOUTH_AMERICA: "남미",
  ANTARCTIC: "남극",
};
